### ISSUE TITLE
这个比crnn准确率高吗

### ISSUE THREAD

**Issue by BADBADBADBOY** [bai-shang/crnn_seq2seq_ocr.PyTorch#3]

**Comment by swordspoet** [comment]
我尝试了一下，比如这两个样本：
![image](https://user-images.githubusercontent.com/14816130/63819570-5a509600-c978-11e9-90a4-fc6ecb448d32.png)
![image](https://user-images.githubusercontent.com/14816130/63819610-83712680-c978-11e9-8629-c3e12506b84d.png)
都无法识别，其实第一张可能噪声比较大，但是第二张图片就属于那种比较标准的印刷体了，使用pytesseract的识别效果很好，都能识别出来。

**Comment by bai-shang** [comment]
> 我尝试了一下，比如这两个样本：
> ![image](https://user-images.githubusercontent.com/14816130/63819570-5a509600-c978-11e9-90a4-fc6ecb448d32.png)
> ![image](https://user-images.githubusercontent.com/14816130/63819610-83712680-c978-11e9-8629-c3e12506b84d.png)
> 都无法识别，其实第一张可能噪声比较大，但是第二张图片就属于那种比较标准的印刷体了，使用pytesseract的识别效果很好，都能识别出来。

此代码只用于分析和讲解基于attention的OCR原理，并不是完整的工程代码。
如果你没有修改代码而直接用于汉字识别，和tesseract比效果很差再正常不过了，毕竟tesseract是一个大开源项目。
基于attention的OCR是有很多很多tricks的，正常情况这种简单的印刷体识别率不会低于99%。

**Comment by swordspoet** [comment]
> > 我尝试了一下，比如这两个样本：
> > ![image](https://user-images.githubusercontent.com/14816130/63819570-5a509600-c978-11e9-90a4-fc6ecb448d32.png)
> > ![image](https://user-images.githubusercontent.com/14816130/63819610-83712680-c978-11e9-8629-c3e12506b84d.png)
> > 都无法识别，其实第一张可能噪声比较大，但是第二张图片就属于那种比较标准的印刷体了，使用pytesseract的识别效果很好，都能识别出来。
> 
> 此代码只用于分析和讲解基于attention的OCR原理，并不是完整的工程代码。
> 如果你没有修改代码而直接用于汉字识别，和tesseract比效果很差再正常不过了，毕竟tesseract是一个大开源项目。
> 基于attention的OCR是有很多很多tricks的，正常情况这种简单的印刷体识别率不会低于99%。工程问题请找工程师。。。

嗯嗯，其实视觉这一块我不大懂，如果想要得到更好的效果应该继续调试模型吧。ps，大佬写得一文读懂faster RCNN很厉害啊。

**Comment by courao** [comment]
> 我尝试了一下，比如这两个样本：
> ![image](https://user-images.githubusercontent.com/14816130/63819570-5a509600-c978-11e9-90a4-fc6ecb448d32.png)
> ![image](https://user-images.githubusercontent.com/14816130/63819610-83712680-c978-11e9-8629-c3e12506b84d.png)
> 都无法识别，其实第一张可能噪声比较大，但是第二张图片就属于那种比较标准的印刷体了，使用pytesseract的识别效果很好，都能识别出来。

这个仓库只是文字识别的不包含文字检测所以必然效果差，要是一步到位可以试试这个代码https://github.com/courao/ocr.pytorch

**Comment by fengheyiyi** [comment]
我想用自己的图训练模型，按照“python3 --train_list train_list.txt --eval_list test_list.txt --model ./model/crnn/ ”出现unknown option --train_list是什么原因呢？

**Comment by shigaimei** [comment]
我就裁剪了一排汉字出来，识别率很低啊，直接word里打了“5%葡萄糖注射液”几个字，直接裁剪出来都完全无法识别，

**Comment by bai-shang** [comment]
> 我就裁剪了一排汉字出来，识别率很低啊，直接word里打了“5%葡萄糖注射液”几个字，直接裁剪出来都完全无法识别，

此代码只是seq2seq+attention做文字谁别的sample code，至于你的工程问题请招聘工程师解决。
